services:
  # --- FMC API ---
  middleware-google-fmc:
    image: michaelrmartins/middleware-google-api:latest
    container_name: middleware-google-fmc
    restart: always
    environment:
      # Tenant Configuration
      - TENANT_ID=${TENANT_ID_FMC}
      - TENANT_NAME=${TENANT_NAME_FMC}
      
      # Database Configuration
      - DB_HOST=postgres
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

      # Google and Email Configuration
      - ADMIN_EMAIL=${ADMIN_EMAIL_FMC}
      - DOMAIN_EMAIL=${DOMAIN_EMAIL_FMC}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/google-credentials.json

      # Server Ip and Port
      - SERVER_IP_ADDRESS=${SERVER_IP_ADDRESS}
      - SERVER_PORT=${SERVER_PORT}

    volumes:
      - /home/cgi/documents/projects/middleware-google-api/google-credentials-fmc.json:/app/google-credentials.json:ro
    networks:
      - shared_services

  # --- FBPN API ---
  middleware-google-fbpn:
    image: michaelrmartins/middleware-google-api:latest
    container_name: middleware-google-fbpn
    restart: always
    environment:
      # Tenant Configuration
      - TENANT_ID=${TENANT_ID_FBPN}
      - TENANT_NAME=${TENANT_NAME_FBPN}

      # Database Configuration
      - DB_HOST=postgres
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - ADMIN_EMAIL=${ADMIN_EMAIL_FBPN}
      - DOMAIN_EMAIL=${DOMAIN_EMAIL_FBPN}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/google-credentials.json

      # Server Ip and Port
      - SERVER_IP_ADDRESS=${SERVER_IP_ADDRESS}
      - SERVER_PORT=${SERVER_PORT}
    volumes:
      - /home/cgi/documents/projects/middleware-google-api/google-credentials-fbpn.json:/app/google-credentials.json:ro
    networks:
      - shared_services

  # --- Database ---
  postgres:
    image: postgres:15-alpine
    container_name: database-main
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /home/cgi/documents/projects/middleware-google-api/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - shared_services
    ports: 
      - "${DB_PORT}:5432"

  # --- (NGINX - Web Page) ---
  middleware-google-web-interface:
    image: michaelrmartins/middleware-google-web-interface:latest
    container_name: middleware-google-web-interface
    depends_on:
      - middleware-google-fmc
      - middleware-google-fbpn
    networks:
      - shared_services

networks:
  shared_services:
    driver: bridge

volumes:
  postgres_data: